type TutorialState = 
      "Salutations"
    | "DraggingCannonInstructions"
    | "ToDragCannon"
    | "DraggedCannon"
    | "DraggingVelocityInstructions"
    | "ToDragVelocity"
    | "DraggedVelocity"
    | "DragHeightArrowInstructions"
    | "ToDragHeightArrow"
    | "DraggedHeightArrow"
    | "ToPanToTarget"
    | "PannedToTarget"
    | "ToFireAtTarget"
    | "FiredAtTarget"
    | "HitTarget"
    | "MissedTarget"
    | "CompletedTutorial"
