type UserState = 
    "default"
  | "draggingCannon" 
  | "draggingVelocity" 
  | "draggingHeightArrow"
  | "inputPanelAngle"
  | "inputPanelVelocity"
  | "inputPanelHeight"
  | "scrolling"
  | "firing"